#ifndef _ALIAS_PGA_REAL_H_
#define _ALIAS_PGA_REAL_H_

#include <alias/math.h>
#include <alias/cpp/boolean.h>

#define ALIAS_PGA_RZ_NEGATE(A) ALIAS_CPP_IF1(ALIAS_CPP_IS_ZERO(A))(0)(-(A))

#define ALIAS_PGA_RZ_ADD(A, B) ALIAS_CPP_IF2(ALIAS_CPP_IS_ZERO(A), ALIAS_CPP_IS_ZERO(B))(0)((B))((A))((A)+(B))
#define ALIAS_PGA_RZ_SUBTRACT(A, B) ALIAS_CPP_IF2(ALIAS_CPP_IS_ZERO(A), ALIAS_CPP_IS_ZERO(B))(0)(-(B))((A))((A)-(B))

#define ALIAS_PGA_RZ_MUL(A, B) ALIAS_CPP_IF2(ALIAS_CPP_IS_ZERO(A), ALIAS_CPP_IS_ZERO(B))()()()((A)*(B))
#define ALIAS_PGA_RZ_ADD_MUL(A, B) ALIAS_CPP_IF2(ALIAS_CPP_IS_ZERO(A), ALIAS_CPP_IS_ZERO(B))()()()(+((A)*(B)))
#define ALIAS_PGA_RZ_SUBTRACT_MUL(A, B) ALIAS_CPP_IF2(ALIAS_CPP_IS_ZERO(A), ALIAS_CPP_IS_ZERO(B))()()()(-((A)*(B)))

#endif

