#ifndef _ALIAS_PGA_SELECT_GRADE_H_
#define _ALIAS_PGA_SELECT_GRADE_H_

#include <alias/pga/unary.h>

#define ALIAS_PGA_UNARY_SELECT_GRADE_0(RETURN, A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, ...) RETURN(A,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, ## __VA_ARGS__)
#define ALIAS_PGA_UNARY_SELECT_GRADE_1(RETURN, A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, ...) RETURN(0,B,C,D,E,0,0,0,0,0,0,0,0,0,0,0, ## __VA_ARGS__)
#define ALIAS_PGA_UNARY_SELECT_GRADE_2(RETURN, A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, ...) RETURN(0,0,0,0,0,F,G,H,I,J,K,0,0,0,0,0, ## __VA_ARGS__)
#define ALIAS_PGA_UNARY_SELECT_GRADE_3(RETURN, A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, ...) RETURN(0,0,0,0,0,0,0,0,0,0,0,L,M,N,O,0, ## __VA_ARGS__)
#define ALIAS_PGA_UNARY_SELECT_GRADE_4(RETURN, A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P, ...) RETURN(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,P, ## __VA_ARGS__)

ALIAS_PGA_GENERATE_UNARY(ALIAS_PGA_UNARY_SELECT_GRADE_0, select_grade_0)
ALIAS_PGA_GENERATE_UNARY(ALIAS_PGA_UNARY_SELECT_GRADE_1, select_grade_1)
ALIAS_PGA_GENERATE_UNARY(ALIAS_PGA_UNARY_SELECT_GRADE_2, select_grade_2)
ALIAS_PGA_GENERATE_UNARY(ALIAS_PGA_UNARY_SELECT_GRADE_3, select_grade_3)
ALIAS_PGA_GENERATE_UNARY(ALIAS_PGA_UNARY_SELECT_GRADE_4, select_grade_4)

#define alias_pga_select_grade_0(A) ALIAS_PGA_USE_UNARY(ALIAS_PGA_UNARY_SELECT_GRADE_0, select_grade_0, A)
#define alias_pga_select_grade_1(A) ALIAS_PGA_USE_UNARY(ALIAS_PGA_UNARY_SELECT_GRADE_1, select_grade_1, A)
#define alias_pga_select_grade_2(A) ALIAS_PGA_USE_UNARY(ALIAS_PGA_UNARY_SELECT_GRADE_2, select_grade_2, A)
#define alias_pga_select_grade_3(A) ALIAS_PGA_USE_UNARY(ALIAS_PGA_UNARY_SELECT_GRADE_3, select_grade_3, A)
#define alias_pga_select_grade_4(A) ALIAS_PGA_USE_UNARY(ALIAS_PGA_UNARY_SELECT_GRADE_4, select_grade_4, A)

#endif

